const input = document.getElementById("input-el")
const meterContainter =  document.getElementById("meters")
const feetContainer =  document.getElementById("feet")
const literContainer = document.getElementById("liters")
const gallonsContainer =  document.getElementById("gallons")
const kiloContainer =  document.getElementById("kilos")
const poundsContainer =  document.getElementById("pounds")
const button = document.getElementById("btn")